# Generated by Django 5.0.2 on 2024-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('A', 'స్తుతి, ఆరాధన, సిలువ ద్యానం'), ('B', 'హెచ్చరిక, దిద్దుబాటు'), ('C', 'ప్రార్థన, విజ్ఞాపన, యాచన'), ('D', 'లేఖన విలువ '), ('E', 'సేవా పిలుపు, సేవా సమర్పణ'), ('F', 'ఆధరణ, ప్రోత్సాహము'), ('G', 'యవనస్థులు'), ('H', 'సోదరీలు'), ('I', 'సువార్త సందేశం, సువార్త పిలుపు'), ('J', 'ప్రభువు రాకడ, రాకడ సిద్ధపాటు '), ('K', 'అనుబంధ కీర్తనలు')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_Number',
            field=models.IntegerField(),
        ),
    ]
